import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })
import Link from 'next/link'
import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import Card from 'react-bootstrap/Card';
import Form from 'react-bootstrap/Form';
import InputGroup from 'react-bootstrap/InputGroup';
import Button from 'react-bootstrap/Button';

export default function Home() {
    return (
        <>

            <Head>
                <title>Property Recode</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <Navbar bg="primary" variant="dark">
                    <Container>
                        <Navbar.Brand href="/">Property Recode</Navbar.Brand>
                        <Nav className="me-auto">
                            <Nav.Link href="/Add-property">ADD PROPERTY</Nav.Link>
                            <Nav.Link href="/">PROPERTY</Nav.Link>
                        </Nav>
                    </Container>
                </Navbar>
                <br />

            </Head>

            <main className={styles.main}>
                <Card>
                    <Card.Body>
                        <p>Add your property</p>
                        <InputGroup className="mb-3">
                            <InputGroup.Text id="basic-addon1">Name:</InputGroup.Text>
                            <Form.Control
                                placeholder="name"
                                aria-label="name"
                                aria-describedby="basic-addon1"
                            />
                        </InputGroup>

                        <InputGroup className="mb-3">
                            <InputGroup.Text id="basic-addon1">ID:</InputGroup.Text>
                            <Form.Control
                                placeholder="ID"
                                aria-label="ID"
                                aria-describedby="basic-addon1"
                            />
                        </InputGroup>
                        <InputGroup.Text id="###">ใส่รูป</InputGroup.Text>
                        <Button className="button" variant="primary" type="submit">
                            Submit
                        </Button>
                    </Card.Body>
                </Card>
            </main>
        </>
    )
}
