import Head from 'next/head'
import { Inter } from '@next/font/google'
const inter = Inter({ subsets: ['latin'] })
import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import Button from 'react-bootstrap/Button';
import Card from 'react-bootstrap/Card';
import React, { useState } from 'react';
import Modal from 'react-bootstrap/Modal';


export default function Home() {
  const [show, setShow] = useState(false);
  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);
  return (
    <>

      <Head>
        <title>Property Recode</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <Navbar bg="primary" variant="dark">
          <Container>
            <Navbar.Brand href="/">Property Recode</Navbar.Brand>
            <Nav className="me-auto">
              <Nav.Link href="/Add-property">ADD PROPERTY</Nav.Link>
              <Nav.Link href="/">PROPERTY</Nav.Link>
            </Nav>
          </Container>
        </Navbar>
        <br />

      </Head>

      <main>

        <div className='propertyItam'>

          <Card style={{ width: '18rem' }}>
            <Card.Img variant="top" src="https://media.tenor.com/zOAWdshu_I0AAAAd/boring-unimpressed.gif" />
            <Card.Body>
              <Card.Title>Name Property1</Card.Title>
              <Card.Text>
                Some quick example text to build on the card title and make up the
                bulk of the card's content.
              </Card.Text>
              <Button variant="primary" onClick={handleShow}>Show</Button>{' '}
             
            </Card.Body>
          </Card>
          <Modal
        show={show}
        onHide={handleClose}
        backdrop="static"
        keyboard={false}
      >
<Card style={{ width: '30rem' }}>
            <Card.Img variant="top" src="https://media.tenor.com/zOAWdshu_I0AAAAd/boring-unimpressed.gif" />
            <Card.Body>
              <Card.Title>Name Property1</Card.Title>
              <Card.Text>
                Some quick example text to build on the card title and make up the
                bulk of the card's content.
              </Card.Text>
<Button variant="secondary" onClick={handleClose}>
                Close
              </Button>
            </Card.Body>
          </Card>
</Modal>


          <Card style={{ width: '18rem'}}>
            <Card.Img variant="top" src="https://media.tenor.com/zOAWdshu_I0AAAAd/boring-unimpressed.gif" />
            <Card.Body>
              <Card.Title>Name Property2</Card.Title>
              <Card.Text>
                Some quick example text to build on the card title and make up the
                bulk of the card's content.
              </Card.Text>
              <Button variant="primary">Show</Button>
            </Card.Body>
          </Card>

          <Card style={{ width: '18rem' }}>
            <Card.Img variant="top" src="https://media.tenor.com/zOAWdshu_I0AAAAd/boring-unimpressed.gif" />
            <Card.Body>
              <Card.Title>Name Property3</Card.Title>
              <Card.Text>
                Some quick example text to build on the card title and make up the
                bulk of the card's content.
              </Card.Text>
              <Button variant="primary">Show</Button>
            </Card.Body>
          </Card>

          <Card style={{ width: '18rem' }}>
            <Card.Img variant="top" src="https://media.tenor.com/zOAWdshu_I0AAAAd/boring-unimpressed.gif" />
            <Card.Body>
              <Card.Title>Name Property4</Card.Title>
              <Card.Text>
                Some quick example text to build on the card title and make up the
                bulk of the card's content.
              </Card.Text>
              <Button variant="primary">show</Button>
            </Card.Body>
          </Card>
        </div>
      </main>
    </>
  )
}
